name: llmulator
channels:
  - nvidia
  - pytorch
  - conda-forge
dependencies:
  - python=3.10
  - pip
  - pytorch
  - pytorch-cuda=12.1
  - numpy
  - scipy
  - scikit-learn
  - pyyaml
  - tqdm
  - tokenizers
  - tensorboard
  - pip:
      - transformers>=4.41.0
      - peft>=0.11.0
      - accelerate>=0.33.0
      - trl>=0.9.6
      - dgl==2.1.0
      - gradio
      - llama-recipes
